### ISSUE TITLE
Create component molecules/Navbar

### ISSUE THREAD

**Issue by FrcGustavo** [MasterChatCenter/frontend#21]
# Task
Create Navbar
This can be diferent, depends on the type of user

### Admin
![image](https://user-images.githubusercontent.com/20009195/91791454-cc396c00-ebd8-11ea-92e1-5bd253bc28cc.png)

### Agent
![image](https://user-images.githubusercontent.com/20009195/91791369-95635600-ebd8-11ea-9cc9-648be21b13b4.png)

 # What type of task is it?
- [x] feature

# Aditional context

**Comment by cenavia** [comment]
components create 0abe6748d6d1f81a6448ee07441af7388e439412 #
