### ISSUE TITLE
Create component atoms/CardBorder

### ISSUE THREAD

**Issue by FrcGustavo** [MasterChatCenter/frontend#27]
# Task
Create CardBorder
padding-top: 15px;
padding-bottom: 15px;

![image](https://user-images.githubusercontent.com/20009195/91793415-c1350a80-ebdd-11ea-973a-b7e3e67c29d0.png)

 # What type of task is it?
- [x] feature

# Aditional context

**Comment by cenavia** [comment]
#44 Create component atoms/CardBorder
