### ISSUE TITLE
Create component molecules/ChatButton

### ISSUE THREAD

**Issue by FrcGustavo** [MasterChatCenter/frontend#28]
# Task

This component receives a **image**, **name**, **status** and **message**

![image](https://user-images.githubusercontent.com/20009195/91793585-39033500-ebde-11ea-8643-543e2a3e77ca.png)

 # What type of task is it?
- [x] feature

# Aditional context

**Comment by cenavia** [comment]
1fdf91d Create component molecules/ChatButton complete
