### ISSUE TITLE
Create conponent organisms/ChatList

### ISSUE THREAD

**Issue by FrcGustavo** [MasterChatCenter/frontend#33]
# Task
This component render a list of chats and render InputSearch

![image](https://user-images.githubusercontent.com/20009195/91801049-c8651400-ebef-11ea-9e58-4f8160588bc3.png)

 # What type of task is it?
- [x] feature
- [x] improvement

# Aditional context

**Comment by cenavia** [comment]
e2a5b58 Create conponent organisms/ChatList - complete
